spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mondatabase?useSSL=false&allowPublicKeyRetrieval=true
    username: monuser
    password: monpassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect